version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app
    environment:
      FLASK_ENV: production

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
